export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_ERROR = 'GET_CURRENT_WEATHER_ERROR';
export const GET_CURRENT_WEATHER_CLEAR = 'GET_CURRENT_WEATHER_CLEAR';

export const GET_HOUR_WEATHER = 'GET_HOURLY_WEATHER';
export const GET_HOUR_WEATHER_SUCCESS = 'GET_HOURLY_WEATHER_SUCCESS';
export const GET_HOUR_WEATHER_ERROR = 'GET_HOURLY_WEATHER_ERROR';
export const GET_HOUR_WEATHER_CLEAR = 'GET_HOURLY_WEATHER_CLEAR';

export const SET_LOCATION = 'SET_LOCATION';
